# Generated by Django 2.1.7 on 2019-06-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('usergroup', '0007_auto_20190320_1909'),
        ('utils', '0001_initial'),
        ('collection', '0002_auto_20190602_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField(auto_now=True, verbose_name='上传日期时间')),
                ('collection',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Collection',
                                   verbose_name='文件集')),
                ('file',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.UploadFile',
                                   verbose_name='文件')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergroup.User',
                                               verbose_name='上传人')),
            ],
            options={
                'verbose_name': '文件集文件',
                'verbose_name_plural': '文件集文件',
            },
        ),
    ]
