# Generated by Django 2.1.7 on 2019-06-03 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0003_collectionfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionfile',
            name='upload_datetime',
        ),
    ]
