# Generated by Django 2.1.7 on 2019-03-03 15:57

import uuid

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninUserInfo',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=32, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(help_text='必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。', max_length=150,
                                              validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                                              verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('qq', models.CharField(max_length=20, verbose_name='QQ')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '注册信息',
                'verbose_name_plural': '注册信息',
            },
        ),
    ]
