# Generated by Django 2.1.7 on 2019-03-03 17:11

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_auto_20190303_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.CharField(default=uuid.uuid1, max_length=36, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '忘记密码',
                'verbose_name_plural': '忘记密码',
            },
        ),
    ]
