# Generated by Django 2.1.7 on 2019-04-02 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_auto_20190305_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signinuserinfo',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False,
                                   verbose_name='ID'),
        ),
    ]
