# Generated by Django 2.1.7 on 2019-03-20 13:23

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='名称')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.CharField(choices=[('0', '不需要登陆'), ('1', '需要登陆已注册'), ('2', '需要登陆未注册')], max_length=10,
                                          verbose_name='类型')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_modified_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('users', models.ManyToManyField(to='usergroup.User')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
            },
        ),
    ]
