# Generated by Django 2.1.7 on 2019-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('usergroup', '0005_auto_20190320_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
