# Generated by Django 2.1.7 on 2019-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('usergroup', '0006_auto_20190320_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='type',
            field=models.CharField(
                choices=[('NONEEDLOGIN', '不需要登陆'), ('ALREADYSIGNIN', '需要登陆已注册'), ('REQUIRESIGNIN', '需要登陆未注册')],
                max_length=20, verbose_name='类型'),
        ),
    ]
